### ISSUE TITLE
Maybe generate hyperlinks explicitly?

### ISSUE THREAD

**Issue by jkuchar** [grifart/phpstan-oneline#3]
inspiration https://github.com/symfony/symfony/pull/29168/files

thanks @TomasVotruba for this suggestion

**Comment by enumag** [comment]
I've [suggested](https://github.com/phpstan/phpstan/issues/1594) this for PHPStan a while ago and @ostrolucky made the SF PR in a reaction to that. The limitation is that those hyperlinks only work in [some terminals](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda?ts=4#supporting-apps). I'm not sure if there is a way to make them work in PHPStorm-embedded console but I didn't try Awesome Console yet.

By the way while I like this extension I think it would be better to use two lines per error (one for link, one for error message) because the relative paths are often quite long. At least until we can use the real hyperlinks. Sadly this suggestion is a bit incompatible with the name of this package. 😄

**Comment by jkuchar** [comment]
It it very badly readable in terminal with soft-wrapping enabled. I do not like it too. 

I consider this project as an experiment and I'm open to add more variations of output to try what works the best. Hopefully the best one will it make it into PhpStan.

**Comment by jkuchar** [comment]
> By the way while I like this extension I think it would be better to use two lines per error (one for link, one for error message) because the relative paths are often quite long.

I was experimenting with this. If you want you can send PR with output named "compact" (which was btw WIP name of this package)

I would also like to try 3 lines - path, error message and one empty

**Comment by enumag** [comment]
I have some time today, give me a sec.

**Comment by jkuchar** [comment]
I have created follow up for other formats to track them separately #4

**Comment by jkuchar** [comment]
Any ideas how to feature detect this? (e.g. to detect if links are supported?)

**Comment by ostrolucky** [comment]
i think black/whitelisting terminals is your best option, like done in https://github.com/symfony/symfony/pull/29668

**Comment by jkuchar** [comment]
That is sad.

**Comment by jkuchar** [comment]
@enumag Any updates? 🙂

**Comment by enumag** [comment]
@jkuchar Unfortunately, none.

**Comment by enumag** [comment]
@jkuchar Ok, good news now. I did some lobbing the last two days and the result is that PHPStorm 2019.2 should support hyperlinks in terminal. 🎉 See https://youtrack.jetbrains.com/issue/IDEA-204536.

**Comment by enumag** [comment]
Links now work when I use the following configuration:

```
	errorFormatter.compact:
		class: Grifart\PhpstanOneLine\CompactErrorFormatter
		arguments:
			format: "]8;;phpstorm://open/?file={absolutePath}&line={line}\\{path}:{line}]8;;\\\n ↳ {error}\n"
```

Of course, I still need this little [fix](https://github.com/grifart/phpstan-oneline/pull/11) for traits.

**Comment by jkuchar** [comment]
@enumag, please could your provide this format as default for `compact` format? 🙂
